---
apache_create_vhosts: true
apache_vhosts_filename: "{{ domain_name }}.conf"
apache_vhosts_template: "vhosts.conf.j2"
apache_ignore_missing_ssl_certificate: false
apache_vhosts:
  - servername: "{{ domain_name }}"
    serveralias: "www.{{ domain_name }}"
    extra_parameters: |
      ProxyPreserveHost On
      ProxyPass / http://localhost:8080/
      ProxyPassReverse / http://localhost:8080/
      ErrorLog ${APACHE_LOG_DIR}/{{ domain_name }}-error.log
      CustomLog ${APACHE_LOG_DIR}/{{ domain_name }}-access.log combined

apache_vhosts_extra_param: |
  ProxyPreserveHost On
  ProxyPass / http://localhost:8080/
  ProxyPassReverse / http://localhost:8080/
  ErrorLog ${APACHE_LOG_DIR}/{{ domain_name }}-error.log
  CustomLog ${APACHE_LOG_DIR}/{{ domain_name }}-access.log combined

apache_vhosts_ssl:
  - {
    servername: "{{ domain_name }}",
    certificate_file: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem",
    certificate_key_file: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem",
    extra_parameters: "{{apache_vhosts_extra_param}}"
  }

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"
apache_mods_enabled:
  - rewrite
  - headers
  - proxy
  - socache_shmcb
  - http2
  - ssl
  - expires
  - proxy_fcgi
  - proxy_http
apache_mods_disabled: []
