---
- hosts: web
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/firewall.yml
    - vars/apache.yml
    - vars/certbot.yml
    - vars/java.yml
    - vars/docker.yml
    - vars/jenkins.yml
    - vars/jenkins_jobs.yml

  vars:
    - domain_name: "{{ lookup('file', 'sensitive/domain_name') }}"
    - is_terraform_run: false

  pre_tasks:
    - name: Wait 5 minutes for APT to complete on newly created instances
      ansible.builtin.pause:
        minutes: 5
      when: is_terraform_run | bool
    - name: Update apt cache.
      apt: update_cache=yes

  roles:
    - role: geerlingguy.firewall
    - role: geerlingguy.apache
    - role: custom_dependencies
    - role: geerlingguy.java
    - role: geerlingguy.docker
    - role: geerlingguy.ansible
    - role: geerlingguy.jenkins
    - role: jenkins_jobs
    - role: geerlingguy.certbot
    - role: geerlingguy.apache

