---
- name: Check that folder is writable
  file:
    path: "{{ dir }}"
    state: directory
    mode: 02771
    recurse: true

- name: Set correct permissions on files in folder
  shell: find "{{ dir }}" -type f ! -perm 0660 -exec chmod 0660 {} \;
