---
- name: pm2 stop
  shell: pm2 stop ecosystem.config.cjs --only dev
  args:
    chdir: "{{ current_dir }}/client/public"

- name: pm2 start
  shell: pm2 start ecosystem.config.cjs --only dev
  args:
    chdir: "{{ current_dir }}/client/public"