---
- name: Ensure domain directory exists
  file:
    path: "{{ releases_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0711

- name: Ensure persistent directory exists
  file:
    path: "{{ persistent_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0711

- name: Ensure storage directory exists
  file:
    path: "{{ persistent_dir }}/storage"
    state: directory
    owner: www-data
    group: www-data
    mode: 0711

- name: Copy storage
  copy:
    src: "{{ source_directory }}/api/storage"
    dest: "{{ persistent_dir }}/"

- include_tasks: tasks/set_owner_and_group.yml
  vars:
    dir_to_chown: "{{ persistent_dir }}/storage"

- include_tasks: tasks/check_that_folder_is_writable.yml
  vars:
    dir_to_check: "{{ persistent_dir }}/storage"