---
- hosts: web
  vars_files:
    - vars/main.yml

  tasks:
    - include: tasks/setup_deploy_folder_structure.yml
      tags: setup_deploy
    - block:
        - include: tasks/register_release_variables.yml
        - include: tasks/create_new_release_dir.yml
        - include: tasks/copy_build.yml
        - include: tasks/mark_release.yml
        - include: tasks/set_owner_and_group.yml dir_to_chown="{{ new_release_dir }}"
        - include: tasks/set_correct_permissions.yml dir="{{ new_release_dir }}"
        - include: tasks/check_that_folder_is_writable.yml dir_to_check="{{ new_release_dir }}/api/bootstrap/cache"
        - include: tasks/link_storage.yml
        - include: tasks/link_env.yml
        - include: tasks/optimize_app.yml
        - include: tasks/migrate_db.yml
        - include: tasks/bless_new_release.yml
        - include: tasks/leave_most_recent_releases.yml
      rescue:
        - include: tasks/rollback.yml