---
apache_create_vhosts: true
apache_vhosts_filename: "{{ domain_name }}.conf"
apache_vhosts_template: "vhosts.conf.j2"
apache_ignore_missing_ssl_certificate: false
apache_vhosts:
   - servername: "{{ domain_name }}"
     serveralias: "www.{{ domain_name }}"
     documentroot: "/var/www/html/{{ domain_name }}/current/api/public"
     extra_parameters: |
      ErrorLog ${APACHE_LOG_DIR}/{{ domain_name }}-error.log
      CustomLog ${APACHE_LOG_DIR}/{{ domain_name }}-access.log combined

      RewriteEngine on
      RewriteCond %{SERVER_NAME} =www.{{ domain_name }} [OR]
      RewriteCond %{SERVER_NAME} ={{ domain_name }}
      RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

apache_vhosts_ssl:
  - {
     servername: "{{ domain_name }}",
     documentroot: "/var/www/html/{{ domain_name }}/current/api/public",
     certificate_file: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem",
     certificate_key_file: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
  }
apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"
apache_mods_enabled:
  - rewrite.load
  - headers.load
  - proxy.load
  - proxy.conf
  - socache_shmcb.load
  - http2.conf
  - http2.load
  - ssl.conf
  - ssl.load
  - rewrite.load
  - expires.load
  - proxy_fcgi.load
  - proxy_http.load
  - wsgi.conf
  - wsgi.load
apache_mods_disabled: []
