---
php_memory_limit: "512M"
php_max_execution_time: "300"
php_max_input_vars: "3000"
php_upload_max_filesize: "256M"
php_session_cookie_lifetime: "20000"
php_session_gc_maxlifetime: "20000"
php_packages:
  - php8.0
  - php8.0-cli
  - php8.0-common
  - php8.0-gd
  - php8.0-mbstring
  - php8.0-pdo
  - php8.0-apcu
  - php8.0-xml
  - php8.0-opcache
  - php8.0-mysql
  - php8.0-curl
  - php8.0-intl
