---
- name: "Install other dependencies."
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl
    - unzip
    - sendmail
    - acl
    - moreutils

- name: "ensure SSH key is generated"
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa

# Set some settings in ~/.gitconfig
- name: Setup git name
  git_config:
    name: user.name
    scope: global
    value: "{{git_username}}"

- name: Setup git user email
  git_config:
    name: user.email
    scope: global
    value: "{{git_email}}"

- name: Ensure directory for website exists
  file:
    path: "/var/www/html/{{ domain_name }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0700'

- name: Copy .env file
  copy:
    src: "sensitive/.env"
    dest: "/var/www/html/{{ domain_name }}/.env"
    owner: www-data
    group: www-data
    mode: '0644'